### ISSUE TITLE
grep suggestions

### ISSUE THREAD

**Issue by Rob--W** [cr/webextaware#14]
The `grep` command is looked up for every new WebExtension. This seems unnecessary and I suggest to cache the result.

`webextaware grep` automatically adds `-E` to the command. This may make sense for the default `grep` on macOS where `-E` is the only powerful RegExp engine, but in GNU grep there is also `-P`. Can you remove `-E` when the `-P` flag is detected among the arguments?

Relevant snippets from `man grep`:

```
   Matcher Selection
       -E, --extended-regexp
              Interpret PATTERN as an extended regular expression (ERE, see below).

       -F, --fixed-strings
              Interpret PATTERN as a list of fixed strings (instead of regular expressions), separated by newlines, any of which is to be matched.

       -G, --basic-regexp
              Interpret PATTERN as a basic regular expression (BRE, see below).  This is the default.

       -P, --perl-regexp
              Interpret the pattern as a Perl-compatible regular expression (PCRE).  This is experimental and grep -P may warn of unimplemented features.
```

> grep  understands  three different versions of regular expression syntax: “basic” (BRE), “extended” (ERE) and “perl” (PCRE).  In GNU grep there is no difference in available functionality between basic and extended syntaxes.  In other implementations, basic regular expressions are less powerful.  The following description applies to extended regular expressions; differences for basic regular expressions are summarized afterwards.  Perl-compatible regular  expressions  give  additional  functionality,  and  are documented in pcresyntax(3) and pcrepattern(3), but work only if PCRE is available in the system.

**Comment by cr** [comment]
> The grep command is looked up for every new WebExtension. This seems unnecessary and I suggest to cache the result.

You're right, but it was a conscious choice because it is ultimately simplistic and doesn't add significant overhead. What's bugging me most is its debug log noise, so I'll eventually move it to a class property and move the checking / logging logic to the mode setup.

> webextaware grep automatically adds -E to the command. This may make sense for the default grep on macOS where -E is the only powerful RegExp engine, but in GNU grep there is also -P. Can you remove -E when the -P flag is detected among the arguments?

It can certainly be done, but I am really reluctant to start with platform-specific grep backends. At this point I am holding back on adding functionality that requires adding significant complexity. The grep subcommand has always been a bit of a quick&dirty hack for quick&dirty answers. You can always unzip the bulk and then run all the tools you like which is also much faster when doing multiple grepping.

Btw, the (legacy) argument parser for the grep subcommand is up for an overhaul anyway. Not sure yet where it will be headed. Passing arguments transparently to `grep -E` was just the obvious, generic choice.

**Comment by Rob--W** [comment]
The keyword in #16 closed this bug, but the second part has not been addressed yet.

I'd also be fine with documenting that `webextaware grep` is equivalent to `grep -E .... -r [temporary zip dir]`, and the recommendation to use `webextaware unzip` if one wants something else.

(for searches over the full database, doing unzip first would make most sense anyway, because waiting for everything to unzip takes quite some time).

**Comment by cr** [comment]
I tried to make a case why adding the complexity of grep argument detection isn't really worth the functional gain. I might sneak-in a grep note in the README piggybacking on a future commit.
